// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SuperMarkerAPI.Data;

#nullable disable

namespace SuperMarkerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250513151319_CompletlyDB")]
    partial class CompletlyDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SuperMarkerAPI.Models.ProductEntity", b =>
                {
                    b.Property<Guid>("IDProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ManufactureDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameProduct")
                        .IsRequired()
                        .HasMaxLength(130)
                        .HasColumnType("nvarchar(130)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("Decimal(18, 2)");

                    b.Property<Guid>("ProductTypeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IDProduct");

                    b.HasIndex("ProductTypeID");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SuperMarkerAPI.Models.ProductTypeEntity", b =>
                {
                    b.Property<Guid>("IDType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IDType");

                    b.ToTable("ProductTypes");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("CustomerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CustomerAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerID");

                    b.HasIndex("PermissionID");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.CustomerPermissionEntity", b =>
                {
                    b.Property<Guid>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<float>("HolidayDiscount")
                        .HasColumnType("real");

                    b.Property<string>("NamePermission")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PermissionID");

                    b.ToTable("CustomerPermissions");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.EmployeeEntity", b =>
                {
                    b.Property<Guid>("EmployeeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EmployeeAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("EmployeePhoneNumber")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<Guid>("PositionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("WarehouseID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeID");

                    b.HasIndex("PositionID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.ImportDetailEntity", b =>
                {
                    b.Property<Guid>("ImportDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IDProduct")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ImportReceiptID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProductEntityIDProduct")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<float>("UnitPrice")
                        .HasColumnType("real");

                    b.HasKey("ImportDetailID");

                    b.HasIndex("IDProduct");

                    b.HasIndex("ImportReceiptID");

                    b.HasIndex("ProductEntityIDProduct");

                    b.ToTable("ImportDetail");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.ImportReceiptEntity", b =>
                {
                    b.Property<Guid>("ImportReceiptID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ImportDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SupplierID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ImportReceiptID");

                    b.HasIndex("EmployeeID");

                    b.HasIndex("SupplierID");

                    b.ToTable("ImportReceipt");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.InvoiceDetailEntity", b =>
                {
                    b.Property<Guid>("InvoiceDetailID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InvoiceID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("InvoiceDetailID");

                    b.HasIndex("InvoiceID");

                    b.HasIndex("ProductID");

                    b.ToTable("InvoiceDetail");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.InvoiceEntity", b =>
                {
                    b.Property<Guid>("InvoiceID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CustomerID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EmployeeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("InvoiceID");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("Invoice");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.PermissionEntity", b =>
                {
                    b.Property<Guid>("PermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PermissionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PermissionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PermissionID");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.PositionEntity", b =>
                {
                    b.Property<Guid>("PositionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PositionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("positionDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PositionID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.Position_Permission_Entity", b =>
                {
                    b.Property<Guid>("PermissionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PositionID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionID", "PositionID");

                    b.HasIndex("PositionID");

                    b.ToTable("PositionPermissions");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.SupplierEntity", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierPhoneNummber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierId");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.Supplier_Product_Entity", b =>
                {
                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SupplierId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("supplier_Product");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.WarehouseEntity", b =>
                {
                    b.Property<Guid>("WarehouseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WarehouseName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("WarehousePhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WarehouseID");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.WarehouseInventoryEntity", b =>
                {
                    b.Property<Guid>("ProductID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("WarehouseID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("ProductID", "WarehouseID");

                    b.HasIndex("WarehouseID");

                    b.ToTable("Inventory");
                });

            modelBuilder.Entity("SuperMarkerAPI.Models.ProductEntity", b =>
                {
                    b.HasOne("SuperMarkerAPI.Models.ProductTypeEntity", "productType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("productType");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.CustomerEntity", b =>
                {
                    b.HasOne("SuperMarket.Core.Entities.CustomerPermissionEntity", "CustomerPermission")
                        .WithMany("Customer")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomerPermission");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.EmployeeEntity", b =>
                {
                    b.HasOne("SuperMarket.Core.Entities.PositionEntity", "Position")
                        .WithMany()
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperMarket.Core.Entities.WarehouseEntity", "Warehouse")
                        .WithMany("Employees")
                        .HasForeignKey("WarehouseID");

                    b.Navigation("Position");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.ImportDetailEntity", b =>
                {
                    b.HasOne("SuperMarkerAPI.Models.ProductEntity", "Products")
                        .WithMany()
                        .HasForeignKey("IDProduct")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperMarket.Core.Entities.ImportReceiptEntity", "ImportReceipt")
                        .WithMany("ImportDetail")
                        .HasForeignKey("ImportReceiptID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperMarkerAPI.Models.ProductEntity", null)
                        .WithMany("importDetailEntities")
                        .HasForeignKey("ProductEntityIDProduct");

                    b.Navigation("ImportReceipt");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.ImportReceiptEntity", b =>
                {
                    b.HasOne("SuperMarket.Core.Entities.EmployeeEntity", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperMarket.Core.Entities.SupplierEntity", "Supplier")
                        .WithMany()
                        .HasForeignKey("SupplierID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.InvoiceDetailEntity", b =>
                {
                    b.HasOne("SuperMarket.Core.Entities.InvoiceEntity", "Invoice")
                        .WithMany("InvoiceDetail")
                        .HasForeignKey("InvoiceID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperMarkerAPI.Models.ProductEntity", "Product")
                        .WithMany("invoiceDetails")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Invoice");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.InvoiceEntity", b =>
                {
                    b.HasOne("SuperMarket.Core.Entities.CustomerEntity", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperMarket.Core.Entities.EmployeeEntity", "Employee")
                        .WithMany("Invoices")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.Position_Permission_Entity", b =>
                {
                    b.HasOne("SuperMarket.Core.Entities.PermissionEntity", "PermissionEntity")
                        .WithMany("Position")
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperMarket.Core.Entities.PositionEntity", "PositionEntity")
                        .WithMany("Permission")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PermissionEntity");

                    b.Navigation("PositionEntity");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.Supplier_Product_Entity", b =>
                {
                    b.HasOne("SuperMarkerAPI.Models.ProductEntity", "ProductEntity")
                        .WithMany("Suppliers")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SuperMarket.Core.Entities.SupplierEntity", "SupplierEntity")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductEntity");

                    b.Navigation("SupplierEntity");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.WarehouseInventoryEntity", b =>
                {
                    b.HasOne("SuperMarkerAPI.Models.ProductEntity", "Products")
                        .WithMany("Inventory")
                        .HasForeignKey("ProductID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SuperMarket.Core.Entities.WarehouseEntity", "Warehouses")
                        .WithMany("Inventory")
                        .HasForeignKey("WarehouseID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("SuperMarkerAPI.Models.ProductEntity", b =>
                {
                    b.Navigation("Inventory");

                    b.Navigation("Suppliers");

                    b.Navigation("importDetailEntities");

                    b.Navigation("invoiceDetails");
                });

            modelBuilder.Entity("SuperMarkerAPI.Models.ProductTypeEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.CustomerPermissionEntity", b =>
                {
                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.EmployeeEntity", b =>
                {
                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.ImportReceiptEntity", b =>
                {
                    b.Navigation("ImportDetail");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.InvoiceEntity", b =>
                {
                    b.Navigation("InvoiceDetail");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.PermissionEntity", b =>
                {
                    b.Navigation("Position");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.PositionEntity", b =>
                {
                    b.Navigation("Permission");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.SupplierEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("SuperMarket.Core.Entities.WarehouseEntity", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
